### ISSUE TITLE
concurrent write to websocket connection

### ISSUE THREAD

**Issue by bytemode** [topfreegames/pitaya#112]
concurrent write to websocket connection
```
	if c.isWriting {
		panic("concurrent write to websocket connection")
	}
	c.isWriting = true
```

when use websocket, we find error code. agent use two goroutine for write websocket conn. but websocket ntoes : Connections support one concurrent reader and one concurrent writer
```
func (a *Agent) Handle() {
	defer func() {
		a.Close()
		logger.Log.Debugf("Session handle goroutine exit, SessionID=%d, UID=%d", a.Session.ID(), a.Session.UID())
	}()

	go a.write()
	go a.heartbeat()
	select {
	case <-a.chDie: // agent closed signal
		return
	}
}
```

https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency
Concurrency ¶
Connections support one concurrent reader and one concurrent writer.
Applications are responsible for ensuring that no more than one goroutine calls the write methods (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON, EnableWriteCompression, SetCompressionLevel) concurrently and that no more than one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage, ReadJSON, SetPongHandler, SetPingHandler) concurrently.
The Close and WriteControl methods can be called concurrently with all other methods.

so we must fix agent.go， use one goroutine to send websocket msg like nano

**Comment by landbed** [comment]
+1 for this issue.

https://github.com/topfreegames/pitaya/tree/26e1c39ec7d99bad80c3bd23133400427d4729f6

```
{"log":"panic: concurrent write to websocket connection\n","stream":"stderr","time":"2019-11-02T16:56:54.597777353Z"}
{"log":"\n","stream":"stderr","time":"2019-11-02T16:56:54.597838639Z"}
{"log":"goroutine 622 [running]:\n","stream":"stderr","time":"2019-11-02T16:56:54.597946975Z"}
{"log":"github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0009bbe20, 0xc0003b0801, 0xc0003b08ec, 0x0, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2019-11-02T16:56:54.598259614Z"}
{"log":"github.com/gorilla/websocket@v1.4.0/conn.go:591 +0x6f6\n","stream":"stderr","time":"2019-11-02T16:56:54.5983714Z"}
{"log":"github.com/gorilla/websocket.(*Conn).WriteMessage(0xc000906840, 0x2, 0xc0003b08ec, 0x4, 0x4, 0xc0009bbea8, 0xffffffffffffffc4)\n","stream":"stderr","time":"2019-11-02T16:56:54.598634536Z"}
{"log":"github.com/gorilla/websocket@v1.4.0/conn.go:752 +0x24c\n","stream":"stderr","time":"2019-11-02T16:56:54.598758377Z"}
{"log":"github.com/topfreegames/pitaya/acceptor.(*wsConn).Write(0xc0008c39e0, 0xc0003b08ec, 0x4, 0x4, 0xbf678b26a12b124e, 0x6095d8cf978, 0x192ede0)\n","stream":"stderr","time":"2019-11-02T16:56:54.599026343Z"}
{"log":"github.com/topfreegames/pitaya/acceptor/ws_acceptor.go:208 +0x59\n","stream":"stderr","time":"2019-11-02T16:56:54.599150269Z"}
{"log":"github.com/topfreegames/pitaya/agent.(*Agent).heartbeat(0xc0008bca80)\n","stream":"stderr","time":"2019-11-02T16:56:54.599225066Z"}
{"log":"github.com/topfreegames/pitaya/agent/agent.go:310 +0x1f8\n","stream":"stderr","time":"2019-11-02T16:56:54.599344443Z"}
{"log":"created by github.com/topfreegames/pitaya/agent.(*Agent).Handle\n","stream":"stderr","time":"2019-11-02T16:56:54.599405221Z"}
{"log":"github.com/topfreegames/pitaya/agent/agent.go:270 +0x95\n","stream":"stderr","time":"2019-11-02T16:56:54.599517359Z"}
```

**Comment by felipejfc** [comment]
Thanks for reporting this! I'll take a look at this issue.

**Comment by Tiper-In-Github** [comment]
This problem has not been completely solved and there are still exceptions.see:[#177](https://github.com/topfreegames/pitaya/issues/177).
