### ISSUE TITLE
RateLimiter construction bug in v2 branch

### ISSUE THREAD

**Issue by Jarvis-Li** [topfreegames/pitaya#180]
Hi, I ran into a bug  while testing rate limiting demo of the v2 branch, here is the output of piyata-cli：
```shell
❯ pitaya-cli
Pitaya REPL Client
>>> connect localhost:3250
Using json client
connected!
>>> request room.ping
>>> sv->pong
>>> request room.ping
>>> sv->pong
>>> request room.ping
>>> sv->pong
>>> request room.ping
>>> ERRO[0009] EOF
```

server log：
```shell
ERRO[0036] Data=
                	room.ping, Error=rate limit exceeded  source=pitaya
DEBU[0036] Session closed, ID=8, UID=, IP=127.0.0.1:47886  source=pitaya
DEBU[0036] Session read goroutine exit, SessionID=8, UID=  source=pitaya
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb1f56c]

goroutine 168 [running]:
github.com/topfreegames/pitaya/v2/acceptorwrapper.(*RateLimiter).GetNextMessage(0xc000200230, 0xe02680, 0xc00014e460, 0xc000420030, 0x0, 0x0)
	/home/jarvis/projects/pitaya_test/pitaya/acceptorwrapper/rate_limiter.go:88 +0x8c
github.com/topfreegames/pitaya/v2/service.(*HandlerService).Handle(0xc0000cc480, 0xdff840, 0xc000200230)
	/home/jarvis/projects/pitaya_test/pitaya/service/handler.go:180 +0x35b
created by github.com/topfreegames/pitaya/v2.(*App).listen.func1
	/home/jarvis/projects/pitaya_test/pitaya/app.go:356 +0x8e
exit status 2
```

corresponding code: 
```go
        if r.shouldRateLimit(now) {
            logger.Log.Errorf("Data=%s, Error=%s", msg, constants.ErrRateLimitExceeded)
            metrics.ReportExceededRateLimiting(r.app.GetMetricsReporters()) // r.app is nil
            continue
        }
```

I think the problem is that acceptor is added by builder.AddAcceptor(), and RateLimitingWrapper requires an app instance, which is not yet created.

**Comment by felipejfc** [comment]
@felippeduran can you take a look?

**Comment by felipejfc** [comment]
should be fixed now!
